// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by the OpenNext build before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

import {
  createStoreSignature,
  FulfillmentMessage,
  StoreCloudflareEnv,
} from "./src/lib/cloudflare-store";

type QueueMessage<T> = {
  body: T;
  ack(): void;
  retry(): void;
};

type QueueBatch<T> = {
  messages: QueueMessage<T>[];
};

const worker = {
  fetch: openNextWorker.fetch,
  async queue(
    batch: QueueBatch<FulfillmentMessage>,
    env: StoreCloudflareEnv,
  ): Promise<void> {
    for (const message of batch.messages) {
      const path = "/internal/store/fulfill";
      const body = JSON.stringify(message.body);
      try {
        const response = await fetch(
          `${env.STORE_API_ROOT.replace(/\/$/, "")}${path}`,
          {
            method: "POST",
            headers: await createStoreSignature(
              env.STORE_API_HMAC_SECRET,
              "POST",
              path,
              body,
            ),
            body,
          },
        );
        if (!response.ok) {
          message.retry();
          continue;
        }
        const now = Math.floor(Date.now() / 1000);
        await env.STORE_DB.prepare(
          "UPDATE store_orders SET status = 'accepted_by_backend', updated_at = ? WHERE order_id = ?",
        )
          .bind(now, message.body.order_id)
          .run();
        message.ack();
      } catch {
        message.retry();
      }
    }
  },
};

export default worker;
